language: node_js
cache: yarn
node_js:
  - "12"
branches:
  only:
    - master
before_install: 
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
matrix:
  include:
    - node_js: 12
      env: TEST_SUIT=unit
      install:
        - yarn install
        - yarn install --cwd react
      script:
        - yarn --cwd node test
    - node_js: 12
      env: TEST_SUIT=lint
      install:
        - yarn install
        - yarn install --cwd react
      script:
        - ./lint.sh
